version: '3.8'
services:

  gateway:
    build: gateway
    image: share-it:gateway
    container_name: share-it-gateway-container
    ports:
      - "8080:8080"
    #  - "8081:8081"  # debug
    depends_on:
      - server
    environment:
      - SHAREIT_SERVER_URL=http://server:9090

  server:
    build: server
    image: share-it:server
    container_name: share-it-server-container
    ports:
      - "9090:9090"
    #  - "9091:9091"  # debug
    depends_on:
      - db
    environment:
    #  - TZ=Europe/Moscow # for postman tests
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/shareit

  db:
    image: postgres:13.7-alpine
    container_name: share-it-db-container
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=shareit
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=iamroot